### PR TITLE
fix: Helm - only default to release namespace for namespaced resources

### LINKED ISSUE #195: Helm - namespace incorrectly assigned for Helm cluster-level resources
We incorrectly assign Chart namespace even for Cluster-level resources. These should not have a namespace:

```
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.22 <<<
------------------------------------------------------------------------------------------
KIND                       NAMESPACE     NAME                                             API_VERSION                         REPLACE_WITH (SINCE)
...
...
StorageClass               default       slow                                             storage.k8s.io/v1beta1              storage.k8s.io/v1 (1.6+)
```

### PR DESCRIPTION
**Pull request by stepanstipl**
This uses discovery client to check if given type of resource is namespaced. Discovery client should be cached, so it's fine to call ServerResourcesForGroupVersion() multiple times.

Fixes #195

### CODE REVIEW

**Comment by dark0dave** [comment]
I think the sonar change is valid: Rename function "Test_isResourceNamespaced" to match the regular expression ^(_|[a-zA-Z0-9]+)$

File: pkg/collector/helm.go [hunk 1]
```diff
@@ -2,12 +2,16 @@ package collector
 
 import (
 	"fmt"
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
```
Comment (dark0dave) [inline pkg/collector/helm.go:5]: not sure about the apimachinery library

File: pkg/collector/helm.go [hunk 2]
```diff
@@ -20,22 +24,39 @@ func parseManifests(manifest string, defaultNamespace string) ([]map[string]inte
...
 
-		results = append(results, manifest)
+		results = append(results, fixed)
 	}
 
 	return results, nil
 }
 
-func fixNamespace(manifest *map[string]interface{}, defaultNamespace string) {
+func fixNamespace(manifest map[string]interface{}, defaultNamespace string, discoveryClient discovery.DiscoveryInterface) map[string]interface{} {
```
Comment (dark0dave) [inline pkg/collector/helm.go:35]: I would prefer the pointer, can't we use the unstructured. can't we deference instead? for 

```
&unstructured.Unstructured{Object: *manifest}
```

**Review by dark0dave — CHANGES_REQUESTED** [review]
Just some small minor changes, looks good other wise

File: pkg/collector/helm.go (hunk 2 above)
Comment (dark0dave) [reply pkg/collector/helm.go:35]: If its used else where ignore me

**Review by dark0dave — APPROVED** [review]
